Feat/forms profile tech
quickfix-team/quickfix pull request #19
Opened 2023-01-10 18:31 UTC by AugustoHeitor

2023-01-10 21:21 UTC, GustavoGussoni commented
"const mensagem" está em português, a partir da linha 56. De acordo com a padronização, não deveria estar em inglês? Se não for um problema já autorizo aqui.

2023-01-11 12:49 UTC, vitor-galdino requested changes
Existe console.logs espalhados pelo código, além também da função onSubmitFunction estar como async mesmo sem a necessidade. Também ressalto o ponto do Gustavo sobre uma const declarada em português.

2023-01-11 12:52 UTC, AugustoHeitor commented
Obrigado, pessoal irei alterar aqui

2023-01-11 13:02 UTC, vitor-galdino approved these changes

2023-01-11 13:03 UTC, merged